anime_header = "Missing parameters\nSyntax: !anime "
anime_main = "Available functions: watched, add, add going, finished, status, waiting, update"
anime_watched_header = "Increment number of watched episodes on specified anime by given number."
anime_watched = f"{anime_header}watched [Name of anime] [Number of episodes]"
anime_watched_types = "[Number of episodes] must be number."
anime_add_header = "Add new, finished anime to database."
anime_add = f"{anime_header}add [Name of anime] [Number of watched episode] [Total number of episodes]"
anime_add_types = "[Number of watched episode] and [Total number of episodes] must be numbers."
anime_add_going_header = "Add new, ongoing anime to database."
anime_add_going = f"{anime_header}add_going [Name of anime] [Number of watched episodes] [Number of current episodes]" \
                  "[Airing day] [Last updated] [Airing hour])"
anime_add_going_types = "[Number of watched episode], [Number of current episodes] and [Airing hour] must be numbers," \
    "[Last updated] must be date in format 'YYYY-MM-DD'"
anime_finished_header = "Remove anime from database."
anime_finished = f"{anime_header}finished [Name of anime]"
anime_transfer_header = "Move anime from ongoing to finished."
anime_transfer = f"{anime_header}transfer [Name of anime]"
anime_change_header = "Change airing hour of ongoing anime."
anime_change = f"{anime_header}change [Name of anime] [New airing hour]"
anime_wrong_function = "Wrong function\nAvailable: watched, add, add_going, finished, status, waiting, update, change" \
                       ",transfer"
workout_sub_too_few = "Type of workout and number is needed."
workout_sub_too_many = "Too many arguments."
workout_sub_wrong_operation = "Wrong type of operation."
workout_wrong_function = "Wrong function\nAvailable: sub, status"
